/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:19 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MPShuffleControllerDataSource <NSObject>
@required
-(id)shuffleController:(id)arg1 identifierForItemAtIndex:(unsigned)arg2;
-(unsigned)shuffleController:(id)arg1 countOfItemIdentifier:(id)arg2 withMaximumCount:(unsigned)arg3;
-(unsigned)itemCountForShuffleController:(id)arg1;

@end

