/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:19 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MPUTransportControlsViewDelegate <NSObject>
@optional
-(void)transportControlsView:(id)arg1 tapOnControlType:(int)arg2;
-(void)transportControlsView:(id)arg1 longPressBeginOnControlType:(int)arg2;
-(void)transportControlsView:(id)arg1 longPressEndOnControlType:(int)arg2;
-(double)transportControlsView:(id)arg1 transportButtonUnhighlightAnimationDurationForControlType:(int)arg2;

@end

