/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:19 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FuseUI/MusicNavigationController.h>
#import <FuseUI/MusicContextualPlaylistPickerDelegate.h>

@class MusicContextualPlaylistPickerViewConfiguration, UIViewController, NSString;

@interface MusicContextualPlaylistPickerViewController : MusicNavigationController <MusicContextualPlaylistPickerDelegate> {

	MusicContextualPlaylistPickerViewConfiguration* _playlistsViewConfiguration;
	UIViewController* _playlistsViewController;
	/*^block*/id _playlistSelectionHandler;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)automaticallyInstallAccountBarButtonItem;
+(char)automaticallyInstallSearchBarButtonItem;
-(int)preferredStatusBarStyle;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLoad;
-(id)initWithPlaylistSelectionHandler:(/*^block*/id)arg1 ;
-(void)_dismissPlaylistPicker;
-(void)playlistPickerDidFinishWithSelectedPlaylist:(id)arg1 ;
@end

