/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:21 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FuseUI/FuseUI-Structs.h>
#import <FuseUI/MusicEntityViewContentDescriptor.h>

@interface MusicEntityViewVerticalLockupContentDescriptor : MusicEntityViewContentDescriptor {

	float _textEdgePadding;

}

@property (assign,nonatomic) float textEdgePadding;              //@synthesize textEdgePadding=_textEdgePadding - In the implementation block
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(float)textEdgePadding;
-(void)setTextEdgePadding:(float)arg1 ;
@end

