/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:16 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MusicMediaProfileHeaderContentViewControllerDelegate <NSObject>
@optional
-(void)mediaProfileHeaderContentViewController:(id)arg1 didUpdateFollowingState:(char)arg2 forStoreID:(long long)arg3;
-(void)mediaProfileHeaderContentViewController:(id)arg1 didSelectContextualActionsButton:(id)arg2;
-(void)mediaProfileHeaderContentViewController:(id)arg1 didSelectEditButton:(id)arg2;
-(void)mediaProfileHeaderContentViewController:(id)arg1 didSelectShareButton:(id)arg2;
-(void)mediaProfileHeaderContentViewControllerDidSelectProfileTitle:(id)arg1;

@end

