/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:12 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FuseUI/MusicProductTracklistTableViewConfiguration.h>

@interface MusicPlaylistTracklistViewConfiguration : MusicProductTracklistTableViewConfiguration
-(id)initWithEntityProvider:(id)arg1 ;
-(char)canDeleteEntityValueContext:(id)arg1 ;
-(char)canMoveEntityValueContext:(id)arg1 ;
@end

