/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:10 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MusicEntityHorizontalLockupViewDelegate <NSObject>
@optional
-(void)horizontalLockupViewDidSelectContextualActionsButton:(id)arg1;
-(void)horizontalLockupViewDidSelectAddButton:(id)arg1 events:(unsigned)arg2;
-(void)horizontalLockupViewDidLayoutSubviews:(id)arg1;
-(void)horizontalLockupView:(id)arg1 didSelectPlayButtonAction:(unsigned)arg2;
-(char)horizontalLockupViewShouldLayoutAsEditing:(id)arg1;

@end

