/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:12 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FuseUI/FuseUI-Structs.h>
#import <UIKit/UICollectionView.h>

@class UITraitCollection;

@interface MusicCollectionView : UICollectionView {

	UITraitCollection* _cachedTraitCollection;

}

@property (assign,nonatomic) id<MusicCollectionViewDelegate> delegate; 
-(id)initWithFrame:(CGRect)arg1 collectionViewLayout:(id)arg2 ;
-(id)traitCollection;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)setLayoutMargins:(UIEdgeInsets)arg1 ;
-(void)tintColorDidChange;
@end

