/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:10 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FuseUI/MusicProductMainViewController.h>

@interface MusicAlbumProductMainViewController : MusicProductMainViewController
-(void)_productHeaderArtistNameTappedAction:(id)arg1 ;
-(void)handleContainerEntityProviderDidInvalidate;
-(void)_handleEntityProviderDidInvalidate;
-(void)handleTracklistEntityProviderDidInvalidate;
-(void)configureProductAdditionalMetadataViewController:(id)arg1 ;
-(id)loadProductHeaderLockupContentDescriptor;
-(id)loadProductTracklistTableViewConfigurationWithTracklistEntityProvider:(id)arg1 ;
-(id)contextualActionsOverrideTracklistEntityProvider;
-(void)toggleProductLikedWithContainerEntityValueContext:(id)arg1 ;
-(void)updateProductHeaderLockupLikedStateWithContainerEntityValueContext:(id)arg1 ;
@end

