/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:22 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FuseUI/FuseUI-Structs.h>
#import <FuseUI/NSCopying.h>

@interface MusicArtworkPlaceholderKey : NSObject <NSCopying> {

	int _integerHeight;
	int _integerScale;
	int _integerWidth;
	float _scale;
	CGSize _size;

}

@property (nonatomic,readonly) float scale;              //@synthesize scale=_scale - In the implementation block
@property (nonatomic,readonly) CGSize size;              //@synthesize size=_size - In the implementation block
-(CGSize)size;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(float)scale;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithSize:(CGSize)arg1 scale:(float)arg2 ;
@end

