/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:12 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary, NSMutableSet;

@interface MusicGenreResourceImagesCatalog : NSObject {

	NSDictionary* _genreMappings;
	NSMutableSet* _unknownGenres;

}
+(id)sharedGenreResourceImagesCatalog;
-(id)init;
-(id)_baseNameOfImageForGenreNamed:(id)arg1 ;
-(id)nameOfImageForGenreNamed:(id)arg1 ;
-(void)registerGenreResouceImages;
-(id)resourceURLForGenreNamed:(id)arg1 ;
@end

