/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:19 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIAlertAction.h>

@class MusicContextualActionsAlertController;

@interface MusicContextualShareAlertAction : UIAlertAction {

	MusicContextualActionsAlertController* _alertController;

}
+(id)actionsForEntityValueContext:(id)arg1 extraInfo:(id)arg2 alertController:(id)arg3 ;
+(id)contextualShareActionWithMusicShareOperation:(id)arg1 ;
@end

