/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:17 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <FuseUI/FuseUI-Structs.h>
#import <FuseUI/MusicMediaQueryDataSource.h>

@class NSArray;

@interface MusicProfileAlbumsDataSource : MusicMediaQueryDataSource {

	NSArray* _sectionEntities;
	vector<_NSRange, std::__1::allocator<_NSRange> >* _sectionRanges;

}
-(unsigned)numberOfSections;
-(char)showsIndexBar;
-(char)usesSections;
-(id)sectionEntities;
-(void)_invalidateCalculatedEntities;
-(id)localizedSectionTitleAtIndex:(unsigned)arg1 ;
-(NSRange)rangeOfSectionAtIndex:(unsigned)arg1 ;
-(id)entities;
@end

