/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:19 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MediaPlayer/MPMediaQueryQueueFeeder.h>

@class MPMediaPlaylist;

@interface MusicQueryQueueFeeder : MPMediaQueryQueueFeeder

@property (nonatomic,retain) MPMediaPlaylist * mixPlaylist; 
+(char)supportsStateRestoration;
-(id)playbackInfoForIdentifier:(id)arg1 ;
-(id)errorResolverForItem:(id)arg1 ;
-(unsigned)realRepeatType;
-(unsigned)realShuffleType;
-(Class)itemClass;
-(void)setMixPlaylist:(MPMediaPlaylist *)arg1 ;
-(MPMediaPlaylist *)mixPlaylist;
@end

