/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:17 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MusicProfileSplitMainViewControllerDelegate <NSObject>
@optional
-(void)profileSplitMainViewControllerContentScrollViewContentSizeDidChange:(id)arg1;
-(void)profileSplitMainViewController:(id)arg1 needsContentForSegmentWithIdentifier:(id)arg2;
-(void)profileSplitMainViewControllerContentScrollViewDidScroll:(id)arg1;
-(void)profileSplitMainViewController:(id)arg1 contentScrollViewWillEndDraggingWithVelocity:(CGPoint)arg2 targetContentOffset:(inout CGPoint*)arg3;

@end

