/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:12 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MusicProfileDetailViewDelegate <NSObject>
@optional
-(void)profileDetailViewDidSelectTitle:(id)arg1;
-(void)profileDetailViewDidSelectContextualActionsButton:(id)arg1;
-(void)profileDetailViewDidSelectEditButton:(id)arg1;
-(void)profileDetailView:(id)arg1 didUpdateFollowingState:(char)arg2;
-(void)profileDetailViewDidSelectShareActionsButton:(id)arg1;

@end

