/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:14 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol NSCoding
@required
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;

@end

