/*
* This header is generated by classdump-dyld 0.7
* on Saturday, November 28, 2015 at 4:14:13 PM Argentina Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/FuseUI.framework/FuseUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SKUIScrollingSegmentedControllerDelegate <NSObject>
@optional
-(void)scrollingSegmentedController:(id)arg1 willDisplayViewControllerAtIndex:(unsigned)arg2;
-(void)scrollingSegmentedController:(id)arg1 didEndDisplayingViewControllerAtIndex:(unsigned)arg2;
-(void)scrollingSegmentedController:(id)arg1 didFocusViewControllerAtIndex:(unsigned)arg2;
-(void)scrollingSegmentedController:(id)arg1 contentScrollViewDidChangeForViewControllerAtIndex:(unsigned)arg2;

@end

